# http -> https
server {
    listen 80;
    server_name enzo-granana.com www.enzo-granana.com;
    return 301 https://$host$request_uri;
}

# www -> https
server {
    listen 443 ssl;
    server_name www.enzo-granana.com;

    ssl_certificate /etc/letsencrypt/live/enzo-granana.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/enzo-granana.com/privkey.pem;

    return 301 https://enzo-granana.com$request_uri;
}

# https
server {
    listen 443 ssl;
    server_name enzo-granana.com;

    ssl_certificate /etc/letsencrypt/live/enzo-granana.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/enzo-granana.com/privkey.pem;

    location / {
        proxy_pass http://localhost:3030;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}