FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY style.css  /usr/share/nginx/html/style.css
COPY resume.pdf /usr/share/nginx/html/resume.pdf
COPY resume.jpg /usr/share/nginx/html/resume.jpg

EXPOSE 80
